Feature/schedule lib
Memorip/memorip-frontend pull request #36
Opened 2023-07-20 06:56 UTC by Suyeong-Lim

## Why need this change?
- 바퀴의 재발명이었던 캘린더 깎기를 포기하고 react-multi-date-picker 로 rage 있는 캘린더 ui 를 추가했습니다

## Key Changes

/schedule
/schedule/plan

페이지 추가 

## To Reviewers
- Todo : tripType (태그 선택 페이지 ), isPublic 조건 추가한 페이지 작업 예정

## ScreenShot
-
<img width="517" alt="스크린샷 2023-07-20 오후 3 54 42" src="https://github.com/Memorip/memorip-frontend/assets/28384562/979e2ff4-5cd4-4303-811d-c7a173c4f267">

## Reference
-

2023-07-26 15:10 UTC, ctdlog requested changes

2023-07-26 15:10 UTC, hyungwookchoi commented on src/components/views/schedule/ScheduleView.tsx
> +import { usePlan } from '@/hooks/usePlane'
오타!

2023-07-26 15:10 UTC, hyungwookchoi commented on src/components/views/schedule/ScheduleView.tsx
> +          <Link href={'schedule/plan'}>
라우팅 경로는 @/constants/route.ts에 추가해서 상수로 관리하면 좋을거 같아요.

2023-07-26 15:10 UTC, hyungwookchoi commented on src/components/views/schedulePlan/SchedulePlanView.tsx
> +    router.push('/schedule/option')
여기도 상수로!

2023-07-26 15:10 UTC, hyungwookchoi commented on src/pages/schedule/option/index.tsx
> +const Type = () => {
ScheduleOption 페이지 같은데 변수명을 Type으로 지으신 이유가 있나용

2023-07-26 15:10 UTC, ctdlog commented on src/components/views/scheduleType/ScheduleOptionView.tsx
> +const Options = {
상수는 컴포넌트 바깥에 constants 파일을 만들어서 분리하면 좋을 것 같아요.

2023-07-26 15:15 UTC, hyungwookchoi requested changes

2023-07-26 15:15 UTC, hyungwookchoi commented on src/components/views/schedulePlan/SchedulePlanView.tsx
> +      : `${convertedDatesArray[0]} - ${convertedDatesArray[convertedDatesArray.length - 1]} / 등록완료`
삼항연산자를 중첩해서 사용하는 것보다는 if 나 if-else 를 쓰는건 어떨가욥

2023-07-26 15:15 UTC, hyungwookchoi commented on src/components/views/schedulePlan/SchedulePlanView.tsx
> +      : `${convertedDatesArray[0]} - ${convertedDatesArray[convertedDatesArray.length - 1]} / 등록완료`
함수명은 getRegistrationStatus, getRegistrationStatusMessage, ... 같은게 적절할거 같아요 (gpt가 알려줌)

2023-07-26 15:15 UTC, hyungwookchoi commented on src/components/views/scheduleType/ScheduleOptionView.tsx
> +}
상수는 컴포넌트 바깥에 constants 파일을 만들어서 분리하면 좋을 것 같아요.

2023-07-26 15:15 UTC, hyungwookchoi commented on src/components/views/scheduleType/ScheduleOptionView.tsx
> +  const [people, setPeople] = React.useState<number>(1)
people 변수의 기본값이 1이고 앞으로도 숫자만 들어올 수 있는거라면, people의 타입이 이미 number로 추론되고 있어서 `<number>`로 타입을 명시해주지 않아도 되지 않을까요?

2023-07-26 15:15 UTC, ctdlog commented on src/components/views/scheduleType/ScheduleOptionView.tsx
> +  }
휴먼 에러를 방지하기 위해서 (파라미터를 입력할 때 오타를 입력할 수 있어서) method의 타입을 string -> 'plus' | 'minus' 로 좁혀주는게 좋을 것 같아요.

2023-07-26 15:15 UTC, ctdlog commented on src/components/views/scheduleType/ScheduleOptionView.tsx
> +  }
method가 minus이고 people이 0일 때, setPeople이 불필요하게 두 번 실행 될 것 같은데 (마지막에 실행된 setPeople이 적용되겠지만) 한번만 호출될 수 있도록 아래처럼 개선하는건 어떨까요?

```ts
setPeople((prev) => (prev > 1 ? prev - 1 : prev));
```

2023-07-26 15:15 UTC, hyungwookchoi commented on src/hooks/usePlane.ts
> +  }
newPlan 변수를 선언하지 않고, 바로 options를 넘겨줘도 되지 않을까요?

```ts 
setPlan((prev) => ({ ...prev, ...options })) 
```

2023-07-27 04:42 UTC, Suyeong-Lim commented on src/hooks/usePlane.ts
> +  }
저는 바보입니다.. 😞

2023-07-27 04:44 UTC, Suyeong-Lim commented on src/components/views/scheduleType/ScheduleOptionView.tsx
> +}
상수 폴더별로 상소 파일 만드는 것보다는 한 파일에서 관리하는거 어떤지 폴더가 넘 많이 늘어나는 것 같아가지고

2023-07-27 04:45 UTC, Suyeong-Lim commented on src/components/views/schedulePlan/SchedulePlanView.tsx
> +      : `${convertedDatesArray[0]} - ${convertedDatesArray[convertedDatesArray.length - 1]} / 등록완료`
나는 먼가 삼항연산자가 더 조타긔!!!! (고집부리기)

2023-07-27 04:45 UTC, Suyeong-Lim commented on src/pages/schedule/option/index.tsx
> +const Type = () => {
ㅠㅜ type 으로 했다가 option 으로 바꿨는데 여기만 깜빡해부렷..

2023-07-27 04:46 UTC, Suyeong-Lim commented on src/components/views/schedulePlan/SchedulePlanView.tsx
> +    router.push('/schedule/option')
와키!

2023-07-27 04:46 UTC, Suyeong-Lim commented on src/components/views/schedule/ScheduleView.tsx
> +          <Link href={'schedule/plan'}>
와키!

2023-07-27 04:46 UTC, Suyeong-Lim commented on src/components/views/schedule/ScheduleView.tsx
> +import { usePlan } from '@/hooks/usePlane'
손꾸락아 ~~ 오타를 내다니 ~~~~ 완룡

2023-07-27 10:51 UTC, ctdlog approved these changes

2023-07-29 07:34 UTC, ctdlog commented
컨플릭만 해결하고 머지해요~!

2023-07-30 07:08 UTC, merged